---
title: "about"
output: html_document
---

#### Inroduction

This is a personal website by Shuyi SHEN.

The website includes Shuyi SHEN's information and three plots using Instacart dataset.

#### Dataset

Instacart: The dataset contains 1,384,617 observations of 131,209 unique users, where each row in the dataset is a product from an order. There is a single order per user in this dataset.

There are 15 variables in this dataset:

order_id: order identifier

product_id: product identifier

add_to_cart_order: order in which each product was added to cart

reordered: 1 if this prodcut has been ordered by this user in the past, 0 otherwise

user_id: customer identifier

eval_set: which evaluation set this order belongs in 

order_number: the order sequence number for this user

order_dow: the day of the week on which the order was placed

order_hour_of_day: the hour of the day on which the order was placed

days_since_prior_order: days since the last order

product_name: name of the product

aisle_id: aisle identifier

department_id: department identifier

aisle: the name of the aisle

department: the name of the department

#### Dashboard and Plotly

There are three plots in the dashboard.

The first one is a barplot-"Order Count in Different Aisles", indicating the count the order from different aisles, using "aisle" variable only.

The second one is pie plots-"Order Distribution in a Week from Three Most Popular aisles", indicating the order of products from three most popular aisles chosen from the first plot in a week of everyday. Three pies means three aisles and different colors means different days of a week. The plot uses "order_dow" and "aisle" variables.

The third one is a line plot-"Order Distribution in a day from Three Most Popular aisles", indicating the order of products from these three aisles in different hours of a day. Three lines means three aisles and the plot uses "order_hour_of_day" and "aisle" variables.


