---
title: "Results from Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(ggplot2)
library(plotly)

instacart<-p8105.datasets::instacart
```

Column {data-width=550}
-----------------------------------------------------------------------

### Order Count in Different Aisles

```{r}
instacart %>% 
  count(aisle) %>% 
  mutate(aisle = fct_reorder(aisle,n)) %>% 
  plot_ly(x=~aisle,y=~n,color=~aisle,type="bar") %>% 
  layout(xaxis=list(title="Aisle"),
         yaxis=list(title="Count of order"))
```

Column {data-width=450}
-----------------------------------------------------------------------

### Order Distribution in a Week from Three Most Popular aisles

```{r}
pie_data<-instacart %>% 
        filter(aisle=="fresh vegetables"|aisle=="packaged vegetables fruits"|aisle=="fresh fruits") %>%
    select(order_dow,aisle) %>%
    group_by(aisle) %>% 
    count(order_dow) %>%
    mutate(
    order_dow=recode(order_dow,"0"="Sunday","1"="Monday","2"="Tuesday","3"="Wednesday","4"="Thursday","5"="Friday","6"="Saturday")
  )

plot_ly() %>% 
  add_pie(data=pie_data,labels=~order_dow,values=~n,name="fresh fruits",
          domain = list(x = c(0, 0.4), y = c(0.4, 1))) %>%
  add_pie(data=pie_data,labels=~order_dow,values=~n,name="fresh vegetables",
          domain = list(x = c(0.6, 1), y = c(0.4, 1))) %>% 
  add_pie(data=pie_data,labels=~order_dow,values=~n,name="packaged fruits vegetables",domain = list(x = c(0.25, 0.75), y = c(0, 0.6)))
```

### Order Distribution in a day from Three Most Popular aisles

```{r}
order_day<-instacart %>%
  filter(aisle=="fresh vegetables"|aisle=="packaged vegetables fruits"|aisle=="fresh fruits") %>%
  select(order_hour_of_day,aisle) %>% 
  group_by(aisle) %>% 
  count(order_hour_of_day) %>% 
  ggplot(aes(x=order_hour_of_day,y=n))+
  geom_line(aes(color=aisle)) 
  
ggplotly(order_day) %>% 
  layout(autosize = F, 
         width = 400, 
         height =280
         ) %>% 
  layout(xaxis=list(title="Day Time"),
         yaxis=list(title="Order Count"),
         legend=list(orientation = "h",   
                     xanchor = "center",  
                     y=-0.5
                     )
         )
```

